

name: action_debug
on:
  push:
    branches:
      - 'action_debug/*'

jobs:
  debug:
    runs-on: ubuntu-20.04
    steps:
    - uses: 4ch12dy/debugger-action@v2.2
      name: debugger
      timeout-minutes: 30
      continue-on-error: true
      with:
        ngrok_token: ${{ secrets.NGROK_TOKEN }}