

name: action_debug
on:
  push

jobs:
  debug:
    runs-on: ubuntu-20.04
    steps:
    - uses: 4ch12dy/debugger-action@v3.0.0
      name: debugger
      timeout-minutes: 30
      continue-on-error: true
      with:
        ngrok_token: ${{ secrets.NGROK_TOKEN }}