name: wlb
on:
  push:
defaults:
  run:
    shell: bash
jobs:
    runs-on: ubuntu-latest
    steps:
    - name: Start SSH via tmate
    uses: P3TERX/ssh2actions@main
    env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}



