name: Release Binary

on:
  push:
    tags:
      - 'v*'  # 例如，v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the binary
        run: |
          ls ./
        
      - name: Upload release asset
        uses: actions/upload-artifact@v4
        with:
          name: test-bin
          path: ./vnc.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download binary artifact
        uses: actions/download-artifact@v4
        with:
          name: test-bin
    
      - name: update release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
          body: "test release bin"
          artifacts: "./vnc.zip"
          allowUpdates: true
          replacesArtifacts: true
